# Generated by Django 4.1.5 on 2023-01-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(max_length=50)),
                ('method', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('nav_factor', models.IntegerField()),
            ],
        ),
    ]
